# Generated by Django 2.1 on 2019-11-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191107_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='years',
            field=models.ManyToManyField(blank=True, to='student.Year'),
        ),
    ]
