# Generated by Django 2.1 on 2019-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20191107_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='years',
        ),
        migrations.AddField(
            model_name='year',
            name='stud',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
    ]
