# Generated by Django 2.1 on 2019-11-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20191107_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='stud',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.ManyToManyField(blank=True, to='student.Year'),
        ),
    ]
